name: WebApp

env:
  ApplicationDir : "./src/UnderTheBrand.sln"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_test_deploy:
    runs-on: windows-latest
    steps:
     - uses: actions/checkout@v2
#---1---
# Для экономии бесплатного времени сборки (2000 мин)
#     - name: Setup .NET Core
#       uses: actions/setup-dotnet@v1
#       with:
#         dotnet-version: 3.1.101
#     - name: Install dependencies
#       run: dotnet restore ${{ env.ApplicationDir }}
#---1---
     - name: Build
       run: dotnet build ${{ env.ApplicationDir }} --configuration Release
     - name: Test
       run: dotnet test ${{ env.ApplicationDir }} --configuration Release
     - name: Deploy
     - uses: akhileshns/heroku-deploy@v3.0.4 # This is the action
#     - uses: actions/heroku-deploy@v1
       with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}} #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}
#          buildpack: "SOME BUILDPACK" #OPTIONAL
#          branch: "YOUR_BRANCH" #OPTIONAL and DEFAULT - 'HEAD' (a.k.a your current branch)
#          dontuseforce: false #OPTIONAL and DEFAULT - false
#          usedocker: false #OPTIONAL and DEFAULT - false
#          appdir: "" #OPTIONAL and DEFAULT - "". This is useful if the api you're deploying is in a subfolder
#          docker_heroku_process_type: "" #OPTIONAL and DEFAULT - "web"
